# Generated by Django 4.2.3 on 2023-08-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ExpTrackerApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense", old_name="name", new_name="description",
        ),
        migrations.RemoveField(model_name="expense", name="category",),
        migrations.RemoveField(model_name="expense", name="date",),
    ]
