# Generated by Django 4.2.3 on 2023-08-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ExpTrackerApp", "0002_rename_name_expense_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("amount", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(name="Expense",),
    ]
